# JPA
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/algo
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'ynkbusiness2024@gmail.com'
    password: 'rwfl lgok ttbn sqcg'
    properties.mail.smtp:
      nickname: 'admin'
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  data:
    redis:
      host: redis-12084.c290.ap-northeast-1-2.ec2.cloud.redislabs.com
      port: 12084
      password: jas6LkHEziDfl3uitg832ftY8t7mqAFe
